version: '3.3'

volumes:
  volume_mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o:    'bind'
      device: ${HOME}/data/mariadb
  volume_wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o:    'bind'
      device: ${HOME}/data/wordpress

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    restart: always
    volumes:
      - volume_mariadb:/var/lib/mysql
    env_file:
      - "./.env"
    networks:
      - docker-network

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    depends_on:
      - mariadb
    volumes:
      - volume_wordpress:/var/www/wordpress
    env_file:
      - "./.env"
    networks:
      - docker-network

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - volume_wordpress:/var/www/wordpress
    env_file:
      - "./.env"
    networks:
      - docker-network

networks:
  docker-network: