version: '3'

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/mariadb/

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: debian:buster
    restart: always
    volumes:
      - ./requirements/mariadb:/var/lib/mysql
    env_file:
      - "./.env"
    ports:
      - "3306:3306"
    networks:
      - docker-network

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: debian:buster
    restart: always
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    env_file:
      - "./.env"
    networks:
      - docker-network


networks:
  docker-network:
    driver: bridge