version: '3.3'

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
          WP_DATABASE_NAME: wordpress
          MYSQL_ROOT_PWD: nonsochemettere
          WP_DATABASE_USR: jackieriz
          WP_DATABASE_PWD: pass
    restart: always
    volumes:
      - /home/jackieriz/data/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - docker-network

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    env_file:
      - "./.env"
    networks:
      - docker-network


networks:
  docker-network:
    driver: bridge